# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4abe4977b81aacd4706ddc57b9a51bead8beba1fd6afb0b87eb86be182021a7c7be3be3b5f6889d5c531c568329f49c859598414869e6b306cf4959c18499cd

test:
  secret_key_base: cdbd106f2343af67fc8cbb4d7d99c35e30c23eb7648e71e5f0748cdd763ecd70e24068e18133f3362fa59ca14a262c20857f64fd759a5837d8b3803ee427b1bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
